name: Documentation Version Release
on:
  push:
    tags:        
      - '*.*.*'

  workflow_dispatch:
    inputs:
      version:
        description: 'Version of documentation to generate and release, x.y.z'     
        required: true
jobs:
  docs-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Set Version ➕
        run: |
          if [ -z ${{ github.event.inputs.version }} ]; then echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV; else echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV; fi
      - name: Release 🌱
        run: |
          VERSION=${RELEASE_VERSION#"v"}
          echo $VERSION to be released...
          cd docs
          cp -r release/latest/ release/${RELEASE_VERSION} 
          if [[ $RELEASE_VERSION =~ ^[[:digit:]]\.[[:digit:]]\.[[:digit:]]$ ]]; then cp -r release/latest/ release/stable; else echo "Not marking version as stable"; fi
          git status
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.DOCUMENTATION_UPDATE_TOKEN }}
          branch: typescript-conversion